# Generated by Django 5.2.4 on 2025-08-30 09:14

from django.db import migrations, models


def create_default_helplines(apps, schema_editor):
    Helpline = apps.get_model('sos', 'Helpline')
    defaults = [
        {"name": "Police", "phone_number": "100"},
        {"name": "Ambulance", "phone_number": "108"},
        {"name": "Fire", "phone_number": "101"},
        {"name": "Women Helpline", "phone_number": "1091"},
    ]
    for d in defaults:
        Helpline.objects.get_or_create(
            name=d["name"], phone_number=d["phone_number"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RunPython(create_default_helplines),
    ]

