# Generated by Django 5.2.4 on 2025-07-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secret_passphrase',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
