# Generated by Django 5.2.4 on 2025-08-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustedcontact',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If ON, SOS alerts will be sent to this contact.'),
        ),
    ]
