# Generated by Django 5.2.4 on 2025-08-20 05:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_helpline_alter_trustedcontact_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpline',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format (e.g., +919876543210).', regex='^\\+?[1-9]\\d{9,14}$')]),
        ),
        migrations.AlterField(
            model_name='trustedcontact',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format (e.g., +919876543210).', regex='^\\+?[1-9]\\d{9,14}$')]),
        ),
        migrations.AlterField(
            model_name='trustedcontact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_trusted_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
