# Generated by Django 5.2.4 on 2025-09-01 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_helpline_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpline',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Helpline number must be either a short code (e.g., 100) or international format (e.g., +919876543210).', regex='^(\\+?[1-9]\\d{9,14}|\\d{3,5})$')]),
        ),
        migrations.AlterField(
            model_name='trustedcontact',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Trusted contact number must be in international format (e.g., +919876543210).', regex='^\\+?[1-9]\\d{9,14}$')]),
        ),
    ]
